version: '3.8'

services:
  ssh-lab:
    build: environments/ssh-lab
    container_name: ssh-lab
    ports:
      - "2222:22"  # Expose container port 22 on host port 2222
    volumes:
      - ./logs/ssh-lab/auth.log:/var/log/auth.log
      # - ./logs/ssh-lab/syslog:/var/log/syslog
    restart: unless-stopped
    tty: true 
    networks:
      - labnet
  
  ftp-lab:
    build: environments/ftp-lab
    container_name: ftp-lab
    ports:
      - "2121:21"
    volumes:
      - ./logs/ftp-lab/vsftpd.log:/var/log/vsftpd.log
    restart: unless-stopped
    tty: true
    networks: 
      - labnet

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    volumes:
      - ./logs/dvwa/apache2/access.log:/var/log/apache2/access.log
      - ./logs/dvwa/apache2/error.log:/var/log/apache2/error.log
      - ./logs/dvwa/mysql/error.log:/var/log/mysql/error.log
    restart: unless-stopped
    tty: true
    networks: 
      - labnet

  attacker:
    build: 
      context: . 
      dockerfile: ./attacker-tools/Dockerfile
    container_name: attacker
    volumes:
      - ./attacker-tools/wordlists/:/wordlists
    networks:
      - labnet

  benign-user:
    build:
      context: .
      dockerfile: ./benign-user/Dockerfile
    container_name: benign_user
    volumes:
      - ./logs:/app/logs
    depends_on:
      - ssh-lab
      - ftp-lab
      - dvwa
    networks:
      - labnet

networks:
  labnet:
    driver: bridge

