version: '3.8'

services:
  ssh-lab:
    build: environments/ssh-lab
    container_name: ssh-lab
    ports:
      - "2222:22"  # Expose container port 22 on host port 2222
    volumes:
      - ./logs/ssh-lab/auth.log:/var/log/auth.log
      - ./logs/ssh-lab/syslog:/var/log/syslog
    restart: unless-stopped
    tty: true 
  ftp-lab:
    build: environments/ftp-lab
    container_name: ftp-lab
    ports:
      - "2121:21"
    volumes:
      - ./logs/ftp-lab/vsftpd.log:/var/log/vsftpd.log
    restart: unless-stopped
    tty: true


