/opt/threat-detection-lab/logs/**/*.log
/opt/threat-detection-lab/logs/**/*.json
/opt/threat-detection-lab/logs/**/*.jsonl {
    size 50M
    rotate 5
    compress
    missingok
    notifempty
    copytruncate
}